# Generated by Django 3.1 on 2021-01-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_educationtype_employeeeducation_employeeexperience_employeelanguage_language_languagelevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexperience',
            name='reason_for_left',
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='reason_of_left',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
